### ISSUE TITLE
No service exposing performance analyzer API on port 9600

### ISSUE THREAD

**Issue by vmm-afonso** [opensearch-project/helm-charts#436]
Hey, so I noticed there were a few changes to the charts with update 2.11.2 concerning performance analyzer. I'm wondering if the performance analyzer plugin comes enabled by default and if the charts are supposed to be creating services exposing performance analyzer API on port 9600? or is it necessary to make changes to my values.yml or any other conf file?

**Comment by jordarlu** [comment]
Hi, @peterzhuamazon or @prudhvigodithi ,please take a look and if any comment, thank you!

**Comment by peterzhuamazon** [comment]
Hi @vmm-afonso .

1. The helm charts is using docker images which have PA enabled by default, but you can disable it upon starting the container by using the env vars here: https://github.com/opensearch-project/opensearch-build/tree/main/docker/release#disable-performance-analyzer-agent-cli-and-related-configurations
2. The 9600 port is already exposed in the chart since this PR: https://github.com/opensearch-project/helm-charts/pull/346

If there is no more questions I will close this issue for now.
Please feel free to re-open it at any time.

Thanks.
